package com.smartthings.searchlight.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Data;
//import org.springframework.data.annotation.Id;
import software.amazon.awssdk.services.dynamodb.datamodeling.DynamoDbAttribute;
import software.amazon.awssdk.services.dynamodb.datamodeling.DynamoDbAutoGeneratedKey;
import software.amazon.awssdk.services.dynamodb.datamodeling.DynamoDbHashKey;
import software.amazon.awssdk.services.dynamodb.datamodeling.DynamoDbTable;

import javax.persistence.Id;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;


@Data
@Entity
@DynamoDBTable(tableName = "Bot")
public class Bot {
    @Id
    @DynamoDbHashKey
    @DynamoDbAutoGeneratedKey
    private long mId;
    private String mName;
    private String mHost;
    private String mClaimCode;
    private boolean mIsDeleted;
    private boolean mIsActive;

    @JsonProperty("id")
    public long getMId() {
        return mId;
    }

    @JsonProperty("name")
    public String getMName() {
        return mName;
    }

    @JsonProperty("host")
    @DynamoDbAttribute
    public String getMHost() {
        return mHost;
    }

    @JsonProperty("claim_code")
    @DynamoDbAttribute
    public String getMClaimCode() {
        return mClaimCode;
    }

    @JsonProperty("is_active")
    @DynamoDbAttribute
    public boolean getMIsActive() {
        return mIsActive;
    }

    @JsonProperty("is_deleted")
    @DynamoDbAttribute
    public boolean getMIsDeleted() {
        return mIsDeleted;
    }

    // Private Default Constructor
    private Bot() {}

    public Bot(String name, String host, String claimCode, boolean isDeleted, boolean isActive) {
        mName = name;
        mHost = host;
        mClaimCode = claimCode;
        mIsActive = isActive;
        mIsDeleted = isDeleted;
    }
}